export const SET_CAROUSEL = "SET_CAROUSEL";
export const GET_FILMLIST = "GET_FILMLIST";
export const SET_FILM_SHOWING = "SET_FILM_SHOWING";
export const SET_FILM_COMING_SOON = "SET_FILM_COMING_SOON";
